name: context

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:    
    - name: "context"
    # 환경변수 사용
      env: 
        COMMIT_ID: ${{github.sha}}
      run: echo "Commit id => $COMMIT_ID"
      
